services:
  mariadb:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  protoseal:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}${DB_NAME}


volumes:
  mariadb-data:
